
/**
 * TinaCMS Client
 * Auto-generated by `tinacms build` — do not edit manually.
 * In dev mode this proxies to http://localhost:4001/graphql
 * In production it reads from the static /admin/index.json
 */
import { createClient } from "tinacms/dist/client";
import type { TinaClient } from "tinacms/dist/client";

const isPreview = process.env.NEXT_PUBLIC_TINA_PUBLIC_CLIENT_ID !== undefined;

export const client: TinaClient<Record<string, never>> = createClient({
  url: process.env.NEXT_PUBLIC_TINA_GRAPHQL_URL || "http://localhost:4001/graphql",
  token: process.env.TINA_TOKEN || "",
  queries: (client) => ({
    page: (vars: { relativePath: string }) =>
      client.request(
        `query PageQuery($relativePath: String!) {
          page(relativePath: $relativePath) {
            id
            title
            subtitle
            ctaLabel
            ctaUrl
            metaDescription
            heroImage
            body
            ghl {
              embedCode
              embedType
            }
          }
        }`,
        { variables: vars }
      ),
    pageList: () =>
      client.request(
        `query PageListQuery {
          pageConnection {
            edges {
              node {
                id
                _sys { filename breadcrumbs }
                title
                subtitle
              }
            }
          }
        }`,
        { variables: {} }
      ),
  }),
});
